Этап 1. Сервис статистики
blaackpanter/java-explore-with-me pull request #1
Opened 2024-06-11 18:25 UTC by blaackpanter

2024-06-12 03:59 UTC, db-exp requested changes

2024-06-12 03:59 UTC, db-exp commented on stat-server/stat-client/src/main/resources/application.properties
> +stat-server.url=http://localhost:9090
тут тоже можно переменную из docker-compose использовать

2024-06-12 03:59 UTC, db-exp commented on stat-server/stat-service/src/main/resources/schema.sql
> +    ip       varchar(128) not null,
тут хватит 40, например

2024-06-12 03:59 UTC, db-exp commented on stat-server/stat-service/src/main/java/ru/practicum/statservice/service/StatServiceImpl.java
> +    @Transactional(propagation = Propagation.REQUIRED)
propagation = Propagation.REQUIRED - как будто тут особой пользы не принесет, можно опустить

2024-06-14 21:57 UTC, blaackpanter commented on stat-server/stat-service/src/main/java/ru/practicum/statservice/service/StatServiceImpl.java
> +    @Transactional(propagation = Propagation.REQUIRED)
поправила

2024-06-14 21:57 UTC, blaackpanter commented on stat-server/stat-service/src/main/resources/schema.sql
> +    ip       varchar(128) not null,
поправила

2024-06-14 22:04 UTC, blaackpanter commented on stat-server/stat-client/src/main/resources/application.properties
> +stat-server.url=http://localhost:9090
stat-client не запускаем в docker-compose

2024-06-15 10:31 UTC, db-exp approved these changes

2024-06-15 20:03 UTC, merged